# Site settings
title: Student Blog
tagline: UC Berkeley CS294

theme:
    # Color for sidebar bar, links, etc
    highlight_color: "#205081" #205081" # "#272935"

# Build settings
markdown: kramdown

# Permalinks
permalink: pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
